apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudvibes.fullname" . }}-config
  labels:
    {{- include "cloudvibes.labels" . | nindent 4 }}
data:
  # Application configuration
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  NEXT_PUBLIC_APP_NAME: {{ .Values.env.NEXT_PUBLIC_APP_NAME | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.env.NEXT_PUBLIC_APP_URL | quote }}
  NEXT_PUBLIC_OPEN_METEO_BASE_URL: {{ .Values.env.NEXT_PUBLIC_OPEN_METEO_BASE_URL | quote }}
  
  # Blue-Green deployment configuration
  BLUE_GREEN_ENABLED: {{ .Values.blueGreen.enabled | quote }}
  ACTIVE_SLOT: {{ include "cloudvibes.activeSlot" . | quote }}
  
  # Health check configuration
  HEALTH_CHECK_PATH: {{ .Values.blueGreen.healthCheck.path | default "/api/health" | quote }}
  
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudvibes.fullname" . }}-secret
  labels:
    {{- include "cloudvibes.labels" . | nindent 4 }}
type: Opaque
data:
  # OpenWeatherMap API key (base64 encoded)
  NEXT_PUBLIC_OPENWEATHER_API_KEY: {{ .Values.env.NEXT_PUBLIC_OPENWEATHER_API_KEY | b64enc | quote }}