apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvibes
  namespace: default
  labels:
    app: cloudvibes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudvibes
  template:
    metadata:
      labels:
        app: cloudvibes
    spec:
      containers:
      - name: cloudvibes
        image: cloudvibes:20250826-214500-7b48e3d
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_APP_NAME
          value: "CloudVibes"
        - name: NEXT_PUBLIC_APP_URL
          value: "https://cloudvibes.org"
        - name: HOSTNAME
          value: "0.0.0.0"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvibes
  namespace: default
  labels:
    app: cloudvibes
spec:
  selector:
    app: cloudvibes
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP