apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvibes-app
  labels:
    app: cloudvibes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudvibes
  template:
    metadata:
      labels:
        app: cloudvibes
    spec:
      containers:
      - name: cloudvibes
        image: cloudvibes:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_OPENWEATHER_API_KEY
          value: "your_openweathermap_api_key_here"
        - name: NEXT_PUBLIC_OPEN_METEO_BASE_URL
          value: "https://api.open-meteo.com/v1"
        - name: NEXT_PUBLIC_APP_URL
          value: "https://cloudvibes.org"
        - name: NEXT_PUBLIC_APP_NAME
          value: "CloudVibes"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvibes-service
  labels:
    app: cloudvibes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: cloudvibes